american = "American"
japanese = "Japanese"
greek = "Greek"
french = "French"
russian = "Russian"
italian = "Italian"
korean = "Korean"
indian = "Indian"
german = "German"
irish = "Irish"
chinese = "Chinese"
viking = "Viking"
spanish = "Spanish"
english = "English"
mexican = "Mexican"
british = "British"
scottish = "Scottish"
polish = "Polish"
old-english = "Old English"
filipino = "Filipino"
welsh = "Welsh"
swedish = "Swedish"
dutch = "Dutch"
australian = "Australian"
gaelic = "Gaelic"
hispanic = "Hispanic"
norwegian = "Norwegian"
brazilian = "Brazilian"
finnish = "Finnish"
icelandic = "Icelandic"
portuguese = "Portuguese"
danish = "Danish"
canadian = "Canadian"
hungarian = "Hungarian"
ancient-greek = "Ancient Greek"
celtic = "Celtic"
czech = "Czech"
serbian = "Serbian"
colombian = "Colombian"
swiss = "Swiss"
